name: vibe-carlo

services:
  vibe-carlo:
    build: .
    restart: unless-stopped
    volumes:
      - /opt/montecarlo:/data
    networks:
      - docklinode

networks:
  docklinode:
    external: true
